### ISSUE TITLE
レビュー_ボストン分析

### ISSUE THREAD

**Issue by masaya1017** [domatsu/study-boston#1]
・外れ値が精度に影響を与えている可能性があります。
CRIM（犯罪）について、全体の75%のデータは3.677083に収まっていますが、max（最大値）は88.976200ということで、一部のデータが外れ値として存在している可能性があります。今回外れ値が存在すると仮定して、サンプル数は506という微妙な数の状況の中で、除外すべきかは一旦除外してみて、再度推測結果を確認してみるのが良いかなと思います。
  
あるデータが外れ値であるかをどう判断するかという場合ですが、よくあるのが、mean（平均値）に対して、std(標準偏差σ）×３に収まらないデータを外れ値とみなすやり方です。
外れ値の確認方法としては今回使用していただいているペアプロット以外にも、箱ひげ図や階級図なども使えると思います。
  
ほかにも、例えば、説明変数が14個ありますが、基本的に説明変数が多いほど精度が下がりやすくなるので、説明変数を絞り込むということも有効だと思います。手法として有名なのは、ランダムフォレストにより、説明変数の重要度を可視化するという手があります。

**Comment by domatsu** [comment]
CRIMについてstd(8.6)×3＝25.8以上のものを外れ値として処理してみました。
結果は75.1%と下がってしまいました。
突出した値に見えますが、価格と相関関係があるという事ですね。

**Comment by domatsu** [comment]
説明変数の絞り込みを実施してみました。
全ての変数について１つずつ減らして結果の増減を検証してみましたが、どれを減らしても結果は下がってしまいました。

**Comment by domatsu** [comment]
上記の結果を22項から25項に追記してコミットしました。
